package entidades;
// Generated 20-abr-2020 1:26:05 by Hibernate Tools 4.3.1



/**
 * Cajero generated by hbm2java
 */
public class Cajero  implements java.io.Serializable {


     private String idCajero;
     private Usuario usuario;

    public Cajero() {
    }

    public Cajero(Usuario usuario) {
       this.usuario = usuario;
    }
   
    public String getIdCajero() {
        return this.idCajero;
    }
    
    public void setIdCajero(String idCajero) {
        this.idCajero = idCajero;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


