package entidades;
// Generated 03-abr-2020 21:52:00 by Hibernate Tools 4.3.1



/**
 * Cajero generated by hbm2java
 */
public class Cajero  implements java.io.Serializable {


     private int idCajero;
     private Usuario usuario;

    public Cajero() {
    }

    public Cajero(int idCajero, Usuario usuario) {
       this.idCajero = idCajero;
       this.usuario = usuario;
    }
   
    public int getIdCajero() {
        return this.idCajero;
    }
    
    public void setIdCajero(int idCajero) {
        this.idCajero = idCajero;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


