package entidades;
// Generated 20-abr-2020 1:26:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String idCliente;
     private Usuario usuario;
     private Set cuentas = new HashSet(0);
     private Set vinculadases = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario) {
        this.usuario = usuario;
    }
    public Cliente(Usuario usuario, Set cuentas, Set vinculadases) {
       this.usuario = usuario;
       this.cuentas = cuentas;
       this.vinculadases = vinculadases;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Set getVinculadases() {
        return this.vinculadases;
    }
    
    public void setVinculadases(Set vinculadases) {
        this.vinculadases = vinculadases;
    }




}


