package entidades;
// Generated 03-abr-2020 21:52:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private Usuario usuario;
     private Set<Vinculadas> vinculadases = new HashSet<Vinculadas>(0);
     private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, Usuario usuario) {
        this.idCliente = idCliente;
        this.usuario = usuario;
    }
    public Cliente(int idCliente, Usuario usuario, Set<Vinculadas> vinculadases, Set<Cuenta> cuentas) {
       this.idCliente = idCliente;
       this.usuario = usuario;
       this.vinculadases = vinculadases;
       this.cuentas = cuentas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set<Vinculadas> getVinculadases() {
        return this.vinculadases;
    }
    
    public void setVinculadases(Set<Vinculadas> vinculadases) {
        this.vinculadases = vinculadases;
    }
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }




}


