package entidades;
// Generated 20-abr-2020 1:26:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda  implements java.io.Serializable {


     private int idMoneda;
     private float tasaDeInteres;
     private Float tipoDeCambio;
     private Set cuentas = new HashSet(0);

    public Moneda() {
    }

	
    public Moneda(int idMoneda, float tasaDeInteres) {
        this.idMoneda = idMoneda;
        this.tasaDeInteres = tasaDeInteres;
    }
    public Moneda(int idMoneda, float tasaDeInteres, Float tipoDeCambio, Set cuentas) {
       this.idMoneda = idMoneda;
       this.tasaDeInteres = tasaDeInteres;
       this.tipoDeCambio = tipoDeCambio;
       this.cuentas = cuentas;
    }
   
    public int getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(int idMoneda) {
        this.idMoneda = idMoneda;
    }
    public float getTasaDeInteres() {
        return this.tasaDeInteres;
    }
    
    public void setTasaDeInteres(float tasaDeInteres) {
        this.tasaDeInteres = tasaDeInteres;
    }
    public Float getTipoDeCambio() {
        return this.tipoDeCambio;
    }
    
    public void setTipoDeCambio(Float tipoDeCambio) {
        this.tipoDeCambio = tipoDeCambio;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


