package entidades;
// Generated 20-abr-2020 1:26:05 by Hibernate Tools 4.3.1



/**
 * Vinculadas generated by hbm2java
 */
public class Vinculadas  implements java.io.Serializable {


     private String vinId;
     private Cliente cliente;
     private Cuenta cuenta;
     private byte owner;

    public Vinculadas() {
    }

    public Vinculadas(String vinId, Cliente cliente, Cuenta cuenta, byte owner) {
       this.vinId = vinId;
       this.cliente = cliente;
       this.cuenta = cuenta;
       this.owner = owner;
    }
   
    public String getVinId() {
        return this.vinId;
    }
    
    public void setVinId(String vinId) {
        this.vinId = vinId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public byte getOwner() {
        return this.owner;
    }
    
    public void setOwner(byte owner) {
        this.owner = owner;
    }




}


